/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9dbacd53-c2c4-4fd1-a087-4d2b71a6337f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_RKflRKjYg",
    "aws_user_pools_web_client_id": "4pjib639f6ebc67525ehprq7ps",
    "oauth": {}
};


export default awsmobile;
